name: Inhuman-insurance-inc-ais-robot-actions
run-name: ${{ github.actor }} create Docker Image
env:
  APP_NAME: 'robot-rpa'
on:
  push:
    branches: [ "main" ]


jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the Docker image for ${{ env.APP_NAME }}
        run: docker build . --file Dockerfile --tag ${{ env.APP_NAME }}

  test:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compose UP
        run: docker compose up -d
