name: Inhuman-insurance-inc-ais-robot-actions
run-name: ${{ github.actor }} create Docker Image
env:
  APP_NAME: 'Inhuman-insurance-inc-ais-robot'
on:
  push:
    branches: [ "main" ]


jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the Docker image for ${{ env.APP_NAME }}
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  test:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: run ci

